application: goburglar
version: 1
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
- url: /static
  static_dir: static

- url: /fetch
  script: _go_app
  login: admin

- url: /_ah/channel/connected/
  script: _go_app

- url: /.*
  script: _go_app
